// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package assets

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed flipRight.png
var FlipRightData []byte
var FlipRight = &fyne.StaticResource{
	StaticName:    "flipRight.png",
	StaticContent: FlipRightData,
}

//go:embed flipLeft.png
var FlipLeftData []byte
var FlipLeft = &fyne.StaticResource{
	StaticName:    "flipLeft.png",
	StaticContent: FlipLeftData,
}

//go:embed flipDown.png
var FlipDownData []byte
var FlipDown = &fyne.StaticResource{
	StaticName:    "flipDown.png",
	StaticContent: FlipDownData,
}

//go:embed flipUp.png
var FlipUpData []byte
var FlipUp = &fyne.StaticResource{
	StaticName:    "flipUp.png",
	StaticContent: FlipUpData,
}

//go:embed no-photo.png
var NoPhotoData []byte
var NoPhoto = &fyne.StaticResource{
	StaticName:    "no-photo.png",
	StaticContent: NoPhotoData,
}
