// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package assets

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed flipRight.png
var FlipRightData []byte
var FlipRight = &fyne.StaticResource{
	StaticName:    "flipRight.png",
	StaticContent: FlipRightData,
}

//go:embed flipLeft.png
var FlipLeftData []byte
var FlipLeft = &fyne.StaticResource{
	StaticName:    "flipLeft.png",
	StaticContent: FlipLeftData,
}

//go:embed flipDown.png
var FlipDownData []byte
var FlipDown = &fyne.StaticResource{
	StaticName:    "flipDown.png",
	StaticContent: FlipDownData,
}

//go:embed flipUp.png
var FlipUpData []byte
var FlipUp = &fyne.StaticResource{
	StaticName:    "flipUp.png",
	StaticContent: FlipUpData,
}

//go:embed no-photo.png
var NoPhotoData []byte
var NoPhoto = &fyne.StaticResource{
	StaticName:    "no-photo.png",
	StaticContent: NoPhotoData,
}

//go:embed palette.png
var PaletteData []byte
var Palette = &fyne.StaticResource{
	StaticName:    "palette.png",
	StaticContent: PaletteData,
}

//go:embed brush.png
var BrushData []byte
var Brush = &fyne.StaticResource{
	StaticName:    "brush.png",
	StaticContent: BrushData,
}

//go:embed eraser.png
var EraserData []byte
var Eraser = &fyne.StaticResource{
	StaticName:    "eraser.png",
	StaticContent: EraserData,
}

//go:embed text.png
var TextData []byte
var Text = &fyne.StaticResource{
	StaticName:    "text.png",
	StaticContent: TextData,
}

//go:embed undo.png
var UndoData []byte
var Undo = &fyne.StaticResource{
	StaticName:    "undo.png",
	StaticContent: UndoData,
}

//go:embed redo.png
var RedoData []byte
var Redo = &fyne.StaticResource{
	StaticName:    "redo.png",
	StaticContent: RedoData,
}

//go:embed crop.png
var CropData []byte
var Crop = &fyne.StaticResource{
	StaticName:    "crop.png",
	StaticContent: CropData,
}

//go:embed apply.png
var ApplyData []byte
var Apply = &fyne.StaticResource{
	StaticName:    "apply.png",
	StaticContent: ApplyData,
}

//go:embed discard.png
var DiscardData []byte
var Discard = &fyne.StaticResource{
	StaticName:    "discard.png",
	StaticContent: DiscardData,
}
